name:                advent-solutions
version:             1.0.0.0
github:              "EmilGedda/Advent-of-Code-2020"
license:             BSD3
author:              "Emil Gedda"
maintainer:          "emil.gedda@emilgedda.se"
copyright:           "2020 Emil Gedda"

extra-source-files:
- LICENSE
- README.md

description:         Please see the README on GitHub at <https://github.com/EmilGedda/Advent-of-code-2020#readme>

dependencies:
- advent
- base          ^>= 4.15
- bytestring    ^>= 0.10
- mtl           ^>= 2.2

default-extensions:
- DataKinds
- GADTs
- FlexibleInstances
- FlexibleContexts
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies

library:
  source-dirs:
    - src
  dependencies:
    - attoparsec              ^>= 0.14
    - containers              ^>= 0.6
    - directory               ^>= 1.3
    - exceptions              ^>= 0.10
    - filepath                ^>= 1.4
    - hashable                ^>= 1.3
    - microlens               ^>= 0.4
    - microlens-th            ^>= 0.4
    - split                   ^>= 0.2
    - time                    ^>= 1.9
    - template-haskell        ^>= 2.17
    - unordered-containers    ^>= 0.2
    - vector                  ^>= 0.12
    - vector-algorithms       ^>= 0.8

tests:
  test:
    main:                     Spec.hs
    source-dirs:              test
    dependencies:
      - advent-solutions
      - tasty                 ^>= 1.4
      - tasty-hunit           ^>= 0.10

benchmarks:
  benchmark:
    ghc-options: -O2 -threaded "-with-rtsopts=-T --nonmoving-gc -A64m"

    main:                     Spec.hs
    source-dirs:              bench
    dependencies:
      - advent
      - advent-solutions
      - exceptions            ^>= 0.10
      - tasty-bench           ^>= 0.3
