name:                advent-solutions
version:             1.0.0.0
github:              "EmilGedda/Advent-of-Code-2020"
license:             BSD3
author:              "Emil Gedda"
maintainer:          "emil.gedda@emilgedda.se"
copyright:           "2020 Emil Gedda"

extra-source-files:
- LICENSE
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/EmilGedda/Advent-of-code-2020#readme>

dependencies:
- base ^>= 4.13

library:
  source-dirs:
    - src
  ghc-options:
    - -O3
    - -Wall
    - -Wno-name-shadowing
    - -Wno-incomplete-patterns
    - -Wno-missing-signatures
  dependencies:
    - advent
    - aeson                   ^>= 1.4
    - attoparsec              ^>= 0.13
    - bytestring              ^>= 0.10
    - containers              ^>= 0.6
    - directory               ^>= 1.3
    - exceptions              ^>= 0.10
    - filepath                ^>= 1.4
    - http-client             ^>= 0.6
    - http-client-tls         ^>= 0.3
    - lens                    ^>= 4.18
    - mtl                     ^>= 2.2
    - string-interpolate      ^>= 0.2
    - regex-tdfa              ^>= 1.3
    - split                   ^>= 0.2
    - time                    ^>= 1.9
    - unordered-containers    ^>= 0.2
    - vector                  ^>= 0.12
    - vector-algorithms       ^>= 0.8
    - wreq                    ^>= 0.5

tests:
  test:
    main:                     Spec.hs
    source-dirs:              test
    ghc-options:
      - -O3
      - -Wall
      - -Wno-name-shadowing
      - -Wno-incomplete-patterns
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-missing-signatures
    dependencies:
      - advent
      - advent-solutions
      - bytestring            ^>= 0.10
      - mtl                   ^>= 2.2
      - tasty                 ^>= 1.2
      - tasty-hunit           ^>= 0.10
