name:                advent-solutions
version:             1.0.0.0
github:              "EmilGedda/Advent-of-Code-2020"
license:             BSD3
author:              "Emil Gedda"
maintainer:          "emil.gedda@emilgedda.se"
copyright:           "2020 Emil Gedda"

extra-source-files:
- LICENSE
- README.md

description:         Please see the README on GitHub at <https://github.com/EmilGedda/Advent-of-code-2020#readme>

dependencies:
- advent
- base          ^>= 4.14
- bytestring    ^>= 0.10
- mtl           ^>= 2.2

library:
  source-dirs:
    - src
  dependencies:
    - attoparsec              ^>= 0.13
    - containers              ^>= 0.6
    - directory               ^>= 1.3
    - exceptions              ^>= 0.10
    - filepath                ^>= 1.4
    - hashable                ^>= 1.3
    - lens                    ^>= 4.19
    - split                   ^>= 0.2
    - time                    ^>= 1.9
    - template-haskell        ^>= 2.16
    - unordered-containers    ^>= 0.2
    - vector                  ^>= 0.12
    - vector-algorithms       ^>= 0.8
    - wreq                    ^>= 0.5

tests:
  test:
    main:                     Spec.hs
    source-dirs:              test
    dependencies:
      - advent-solutions
      - tasty                 ^>= 1.2
      - tasty-hunit           ^>= 0.10
